theme = "catppuccin_frappe"

[editor]
true-color = true
line-number = "relative"
undercurl = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
insert-final-newline = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

# [editor]
# end-of-line-diagnostics = "error"
# [editor.inline-diagnostics]
# cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
"ยง" = ":toggle lsp.display-inlay-hints"
Meta-s = ":w"

[keys.normal]
"ยง" = ":toggle lsp.display-inlay-hints"
Meta-s = ":w"
"'" = ":buffer-previous"
"\\" = ":buffer-next"

X = "select_line_above"

[keys.select]
X = "select_line_above"
